### ISSUE TITLE
[Question] should I register sku in some google play console like appstore management system ?

### ISSUE THREAD

**Issue by shaobin0604** [AppStoreFoundation/asf-iab-sample#4]
I'm working on integrating asf iab. 

The purchase flow is much like google IAB, but where should I register all available Skus ? is there any appstore management system like google play console ?

**Comment by JoaoRaimundo** [comment]
Hi shaobin0604,

In our IAB flow the SKUs serves only the purpose to identify the item being bought. This identification is only relevant for you and your app. Basically the identification for the SKUs stays only on your side.
So for managing that kind of information, as an example, you can have your own web service that contains all the items your app allows to be purchased, with names and values.  
When sent to the wallet, the SKU is added to the information registered on the blockchain, later you can use that identification to check on the blockchain what item was bought with a given wallet address.

No appstore management for purchasable items is available, that management is the app's developer responsibility.

**Comment by shaobin0604** [comment]
@JoaoRaimundo Thanks for your explanation
